---
title: "HD_Step1_1_RT"
output:
  word_document: default
  pdf_document: default
---
```{r}
library(readr)
library(psych)
library(tidyr)
library(nlme)
library(multcomp)
library(ggpubr)
library(ggplot2)
library(lme4)
library(lsmeans)
library(afex)
library(dplyr)
library(stargazer)
```
descriptive stats
```{r}
Logfile <- read_csv("~/Desktop/Handedness/Data/Step1/SLR_SDGesture.csv")
#View(Logfile)
str(Logfile)
summary(Logfile)
```

1. Hand Type (Same: Left, Right) * Handedness(Lefty, Righty)
```{r}
Logfile$subject <- as.factor(Logfile$subject)
#str(Logfile)
# define between and within subjects variables
Logfile$handedness <- factor(Logfile$handedness,
                                            levels = c(0,1),
                                            labels = c("Lefty","Righty"))

Logfile$Lat2 <- factor(Logfile$Lat2,
                                            levels = c(0,1),
                                            labels = c("Lefty","Righty"))

Logfile$Strength <- factor(Logfile$Strength,
                                            levels = c(0,1),
                                            labels = c("Mixed","Extreme"))

Logfile$sex <- factor(Logfile$sex,
                                            levels = c(0,1),
                                            labels = c("Female","Male"))

Logfile$version <- factor(Logfile$version,
                                         levels = c(1,2),
                                         labels = c("Response with Left Finger","Response with Right Finger"))

Logfile$synchronicity <- factor(Logfile$synchronicity,
                                         levels = c(0,1),
                                         labels = c("Match","Mismatch"))

Logfile$SLR <- factor(Logfile$SLR,
                                          levels = c(0,1),
                                          labels = c("Left Hands","Right Hands"))

Logfile$SDGesture <- factor(Logfile$SDGesture,
                                          levels = c(0,1),
                                          labels = c("Same Gesture","Different Gesture"))

Logfile$Strategy <- factor(Logfile$Strategy,
                                          levels = c(0,1,2),
                                          labels = c("Mental Rotation","Thumb Strategy","Both"))


#final check the data 
str(Logfile)
View(Logfile)
# Get descriptives
Means.Table<-describe(Logfile)

Means.Table #call the object to see the means table

#use knitr function to call the object to see the means table.
knitr::kable(Means.Table, digits = 2, caption = 'Mixed Means Table')


```


** descriptive analysis **
```{r}

LH <- filter(Logfile, SLR == "Left Hands")
psych::describe(LH$RT)

RH <- filter(Logfile, SLR == "Right Hands")
psych::describe(RH$RT)

```


** formal analysis **
```{r}
SLR_Lat2_Strength_rt <- aov_car(RT~SLR*Lat2*Strength+
            Error(subject/(SLR)),  data=Logfile, anova_table = list(es = "pes"))  

knitr::kable(nice(SLR_Lat2_Strength_rt)) ##call for formatted ANOVA table using knitr

```

```{r}
SLR_Lat2_Strength_rt_Interaction_2 <-lsmeans(SLR_Lat2_Strength_rt, ~(SLR*Lat2*Strength))
SLR_Lat2_Strength_rt_Interaction_2
```

```{r}
pairs(SLR_Lat2_Strength_rt_Interaction_2)
```

**SDGesture**

```{r}
SLR_Lat2_Strength_SDGesture_rt <- aov_car(RT~SLR*Lat2*Strength*SDGesture+
            Error(subject/(SLR*SDGesture)),  data=Logfile, anova_table = list(es = "pes"))  

knitr::kable(nice(SLR_Lat2_Strength_SDGesture_rt)) ##call for formatted ANOVA table using knitr

```

```{r}
SLR_Lat2_Strength_SDGesutre_rt_Interaction_2 <-lsmeans(SLR_Lat2_Strength_SDGesture_rt, ~(SLR*SDGesture)|(Lat2*Strength))
SLR_Lat2_Strength_SDGesutre_rt_Interaction_2
```

```{r}
pairs(SLR_Lat2_Strength_SDGesutre_rt_Interaction_2)
```

*version*
```{r}
SLR_Lat2_Strength_version_rt <- aov_car(RT~SLR*Lat2*version*Strength+
            Error(subject/SLR),  data=Logfile, anova_table = list(es = "pes"))  

knitr::kable(nice(SLR_Lat2_Strength_version_rt)) ##call for formatted ANOVA table using knitr

```
```{r}
SLR_Strength_version_rt_Interaction<-lsmeans(SLR_Lat2_Strength_version_rt, ~SLR|(version*Strength))
SLR_Strength_version_rt_Interaction
pairs(SLR_Strength_version_rt_Interaction)
```

```{r}
LH <- filter(Logfile, SLR == "Left Hands")
psych::describe(LH$RT)

RH <- filter(Logfile, SLR == "Right Hands")
psych::describe((RH$RT))
```

** strategy **

```{r}
STR <- filter(Logfile, Strategy == "Mental Rotation"|Strategy == "Thumb Strategy")
```

```{r}
SLR_Lat2_Strength_Strategy_rt <- aov_car(RT~SLR*Lat2*Strength*Strategy+
            Error(subject/(SLR)),  data=STR, anova_table = list(es = "pes"))     

knitr::kable(nice(SLR_Lat2_Strength_Strategy_rt)) ##call for formatted ANOVA table using knitr
```

