---
title: "Handedness_Step1_3_1RT"
output:
  word_document: default
  pdf_document: default
---
```{r}
library(readr)
library(psych)
library(tidyr)
library(nlme)
library(multcomp)
library(ggpubr)
library(ggplot2)
library(lme4)
library(lsmeans)
library(afex)
library(dplyr)
```
descriptive stats
```{r}
Logfile <- read_csv("~/Desktop/Handedness/Data_new/Step1/SLR_GestureType.csv")
View(Logfile)
str(Logfile)
summary(Logfile)
```

```{r}

Logfile$subject <- as.factor(Logfile$subject)
str(Logfile)
# define between and within subjects variables

# define between and within subjects variables
Logfile$handedness <- factor(Logfile$handedness,
                                            levels = c(0,1),
                                            labels = c("Lefty","Righty"))

Logfile$Lat2 <- factor(Logfile$Lat2,
                                            levels = c(0,1),
                                            labels = c("Lefty","Righty"))

Logfile$Strength <- factor(Logfile$Strength,
                                            levels = c(0,1),
                                            labels = c("Mixed","Extreme"))

Logfile$sex <- factor(Logfile$sex,
                                            levels = c(0,1),
                                            labels = c("Female","Male"))

Logfile$version <- factor(Logfile$version,
                                         levels = c(1,2),
                                         labels = c("Response with Left Finger","Response with Right Finger"))

#Logfile$synchronicity <- factor(Logfile$synchronicity,
 #                                        levels = c(0,1),
  #                                       labels = c("Synchronous","Asynchronous"))

Logfile$SLR <- factor(Logfile$SLR,
                                          levels = c(0,1),
                                          labels = c("Left Hands","Right Hands"))


#Logfile$GestureType <- factor(Logfile$GestureType,
 #                                         levels = c(0,1),
  #                                        labels = c("Palm","Pointer"))

Logfile$Strategy <- factor(Logfile$Strategy,
                                          levels = c(0,1,2),
                                          labels = c("Mental Rotation","Thumb Strategy","Both"))

#final check the data 
str(Logfile)
View(Logfile)
# Get descriptives
Means.Table<-describe(Logfile)

Means.Table #call the object to see the means table

#use knitr function to call the object to see the means table.
knitr::kable(Means.Table, digits = 2, caption = 'Mixed Means Table')

```
** 2 way ANOVA**

```{r}
SLR_Lat2_rt <- aov_car(RT~SLR*Lat2+
            Error(subject/(SLR)),  data=Logfile, anova_table = list(es = "pes"))  

knitr::kable(nice(SLR_Lat2_rt)) ##call for formatted ANOVA table using knitr

```

**REST PART**

```{r}
SLR_Lat2_Strength_rt <- aov_car(RT~SLR*Lat2*Strength+
            Error(subject/(SLR)),  data=Logfile, anova_table = list(es = "pes"))  

knitr::kable(nice(SLR_Lat2_Strength_rt)) ##call for formatted ANOVA table using knitr

```


```{r}
SLR_Lat2_Strength_rt_Interaction<-lsmeans(SLR_Lat2_Strength_rt, ~SLR|(Lat2*Strength))
SLR_Lat2_Strength_rt_Interaction
```

```{r}
pairs(SLR_Lat2_Strength_rt_Interaction)
```

```{r}
update(pairs(SLR_Lat2_Strength_rt_Interaction, by = "SLR"), by = NULL)
```

```{r}

LT <- filter(Logfile, Lat2 == "Lefty")
levels(LT$Strength)[levels(LT$Strength)=="Mixed"] <- "Mixed Left-hander"
levels(LT$Strength)[levels(LT$Strength)=="Extreme"] <- "Extreme Left-hander"

RT <- filter(Logfile, Lat2 == "Righty")
levels(RT$Strength)[levels(RT$Strength)=="Mixed"] <- "Mixed Right-hander"
levels(RT$Strength)[levels(RT$Strength)=="Extreme"] <- "Extreme Right-hander"

pd <- position_dodge(0.1) # move them .05 to the left and right
p_LT <-ggplot(data = LT,aes(x = Strength, color = as.factor(SLR), group = SLR, y = RT)) +
  stat_summary(fun.y = mean, geom = "point", size =5, shape=21, fill="white") +
  stat_summary(fun.y = mean, geom = "line", size = 1.2) +
  stat_summary(fun.data = "mean_se", geom="errorbar", width = .5, position = pd) +
  scale_x_discrete(limits = c("Extreme Left-hander", "Mixed Left-hander"), labels = function(labels){
    fixedLabels <- c()
    for (l in 1:length(labels)){
      fixedLabels[l] <-paste0(ifelse(l %% 2 == 0, '', '\n'), labels[l])
    }
    return(fixedLabels)
  })+
  scale_y_continuous(breaks = seq(0, 9500, by=1000), limits=c(0,9500))+
  labs(x= "Strength", y="RT(ms)", color="", fill="Hand-tested")  + theme_classic() +     
  theme(text=element_text(face="bold", size=20), legend.position = "none", axis.title.x=element_blank())

p_RT <-ggplot(data = RT,aes(x = Strength, color = as.factor(SLR), group = SLR, y = RT)) +
  stat_summary(fun.y = mean, geom = "point", size =5, shape=21, fill="white") +
  stat_summary(fun.y = mean, geom = "line", size = 1.2) +
    scale_x_discrete(labels = function(labels){
    fixedLabels <- c()
    for (l in 1:length(labels)){
      fixedLabels[l] <-paste0(ifelse((l+1) %% 2 == 0, '', '\n'), labels[l])
    }
    return(fixedLabels)
  })+
  stat_summary(fun.data = "mean_se", geom="errorbar", width = .5, position = pd) +
  scale_y_continuous(breaks = seq(0, 9500, by=1000), limits=c(0,9500), position = "right")+
  #scale_y_continuous(breaks = seq(0, 10000, by=1000), position = "right")+
  labs(color="", fill="Hand-tested")  + theme_classic() +     
  theme(text=element_text(face="bold", size=20), axis.title.y=element_blank(), axis.text.y=element_blank(),
  axis.title.x=element_blank()) + annotate("text", x = 1, y = 3800, label = "*", color = "black", size = 16)


Figure5b <- ggarrange(p_LT, p_RT, widths = c(0.8, 1),
                ncol = 2, nrow = 1)


Figure5b

ggsave("5b.png", width = 10, height = 6)
```

```{r}
pd <- position_dodge(0.1) # move them .05 to the left and right

p<-ggplot(data = Logfile,aes(x = Strength, color = as.factor(SLR), group = SLR, y = RT)) +
  stat_summary(fun.y = mean, geom = "point", size =5, shape=21, fill="white") +
  stat_summary(fun.y = mean, geom = "line", size = 1.2) +
  stat_summary(fun.data = "mean_se", geom="errorbar", width = .5, position = pd) +
  scale_y_continuous(breaks = seq(0, 5000, by=1000), limits=c(2000,5000))+
  facet_wrap(~Lat2) +labs( x= "Strength", y="RT(ms)", color="", fill="Hand-tested")  + theme_classic() + theme(text=element_text(face="bold", size=23))

# add significance level labels
dat_text <- data.frame(
  label = "*",
  SLR   = "Significance",
  Lat2 = factor("Lefty", levels = c("Lefty","Righty")),
  Strength = factor("Extreme", levels = c("Extreme", "Mixed")),
  RT     = c(4000)
)

p <- 
  p + geom_text(
    data    = dat_text,
    mapping = aes(x = Strength, y = RT, label = label, size = label)
    )+
    scale_colour_manual(
      values=c("#A8E370","#FF5733","black"))+
    scale_size_manual(
    values = c(10), guide = FALSE)
p
ggsave("SS_RT.pdf")
```

```{r}
# p1 <- ggplot(data = Logfile,aes(x = Strength$Lefty, color = as.factor(SLR), group = SLR, y = RT)) +
#   stat_summary(fun.y = mean, geom = "point", size =5, shape=21, fill="white") +
#   stat_summary(fun.y = mean, geom = "line", size = 1.2) +
#   stat_summary(fun.data = "mean_se", geom="errorbar", width = .5, position = pd) +
#   scale_y_continuous(breaks = seq(0, 5000, by=1000), limits=c(2000,5000))
# 
# p1

# use filter/select function to get the correct data
# look up ggpubr make side by side graphs
```

*gesturetype*

```{r}
# SLR_Lat2_Strength_rt <- aov_car(RT~SLR*Lat2*Strength*GestureType+
#             Error(subject/(SLR*GestureType)),  data=Logfile, anova_table = list(es = "pes"))  
# 
# knitr::kable(nice(SLR_Lat2_Strength_rt)) ##call for formatted ANOVA table using knitr

```

```{r}
acc_Interaction1 <-lsmeans(SLR_Lat2_Strength_rt, ~SLR|(Lat2*Strength))
acc_Interaction1
```

```{r}
pairs(acc_Interaction1)
```

```{r}
update(pairs(acc_Interaction1, by = "SLR"), by = NULL)
```


```{r}
#acc_Interaction2 <-lsmeans(SLR_Lat2_Strength_rt, ~SLR|(GestureType*Strength))
#acc_Interaction2
```

```{r}
# pairs(acc_Interaction2)
```

```{r}
# update(pairs(acc_Interaction2, by = "SLR"), by = NULL)
```
**RT Version**

```{r}
SLR_Lat2_Strength_version_rt <- aov_car(RT~SLR*Lat2*version*Strength+
            Error(subject/SLR),  data=Logfile, anova_table = list(es = "pes"))  

knitr::kable(nice(SLR_Lat2_Strength_version_rt)) ##call for formatted ANOVA table using knitr

```
```{r}
SLR_Lat2_Strength_version_rt_Interaction<-lsmeans(SLR_Lat2_Strength_version_rt, ~SLR|(Lat2*Strength))
SLR_Lat2_Strength_version_rt_Interaction
```

```{r}
pairs(SLR_Lat2_Strength_version_rt_Interaction)
```

```{r}
update(pairs(SLR_Lat2_Strength_version_rt_Interaction, by = "SLR"), by = NULL)
```

** strategy **

```{r}
STR <- filter(Logfile, Strategy == "Mental Rotation"|Strategy == "Thumb Strategy")
```

```{r}
SLR_Lat2_Strength_Strategy_rt <- aov_car(RT~SLR*Lat2*Strength*Strategy+
            Error(subject/(SLR)),  data=STR, anova_table = list(es = "pes"))     

knitr::kable(nice(SLR_Lat2_Strength_Strategy_rt)) ##call for formatted ANOVA table using knitr
```
```{r}
SLR_Lat2_Strength_Interaction<-lsmeans(SLR_Lat2_Strength_rt, ~(SLR|Lat2*Strength))
SLR_Lat2_Strength_Interaction
```
```{r}
pairs(SLR_Lat2_Strength_Interaction)
```
```{r}
update(pairs(SLR_Lat2_Strength_Interaction, by = "SLR"), by = NULL)
```

```{r}
SLR_Lat2_Strength_Strateg_Interaction<-lsmeans(SLR_Lat2_Strength_Strategy_rt, ~(SLR|Lat2*Strength*Strategy))
SLR_Lat2_Strength_Strateg_Interaction
```
```{r}
pairs(SLR_Lat2_Strength_Strateg_Interaction)
```
```{r}
update(pairs(SLR_Lat2_Strength_Strateg_Interaction, by = "SLR"), by = NULL)
```

